apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: private-registry
spec:
  secretName: private-registry-cert
  dnsNames:
  - registry.app.eirini.paulczar.wtf
  acme:
    config:
    - dns01:
        provider: prod-clouddns
      domains:
        - registry.app.eirini.paulczar.wtf
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
